### ISSUE TITLE
Super Stacker

### ISSUE THREAD

**Issue by AnthonyGriffith** [Arcadeacon/Arcadeacon#28]
Super Stacker

http://www.thegamehomepage.com/play/super-stacker/

**Comment by TadeoKondrak** [comment]
http://media1.thegamehomepage.com/swf/1_0554_SuperStacker600x550.swf

**Comment by TadeoKondrak** [comment]
I've added this game in 62acad39e3016c8b86307709de62f8e22f6e30d7.
