### ISSUE TITLE
sir shield!

### ISSUE THREAD

**Issue by JustinWeisser** [Arcadeacon/Arcadeacon#48]
https://scratch.mit.edu/projects/55416430/?fromexplore=true

**Comment by TadeoKondrak** [comment]
<iframe allowtransparency="true" width="485" height="402" src="//scratch.mit.edu/projects/embed/55416430/?autostart=false" frameborder="0" allowfullscreen></iframe>

**Comment by TadeoKondrak** [comment]
replace the iframe line with that
